---
name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:main-amd64, ${{ env.IMAGE_NAME }}:latest-amd64
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

  build_arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:main-arm64, ${{ env.IMAGE_NAME }}:latest-arm64
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64

  create_manifest:
    runs-on: ubuntu-latest
    needs: [build_amd64, build_arm64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          # Create and push main manifest
          docker manifest create ${{ env.IMAGE_NAME }}:main \
            ${{ env.IMAGE_NAME }}:main-amd64 \
            ${{ env.IMAGE_NAME }}:main-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:main
          
          # Create and push latest manifest
          docker manifest create ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:latest-amd64 \
            ${{ env.IMAGE_NAME }}:latest-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:latest

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: "Interactive Streamlit application for analyzing SRT session statistics"
          readme-filepath: ./README.md
