---
name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build --tag ${{ env.IMAGE_NAME }}:latest --file Dockerfile . --no-cache
      
      - name: Test the Docker image
        run: docker run -d -p 8501:8501 --name srt-processor ${{ env.IMAGE_NAME }}:latest

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:main, ${{ env.IMAGE_NAME }}:latest
  
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dbono711/srt-processor
          short-description: "Streamlit application for processing SRT session statistics"
